# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: gittools.gitversion.gitversion-task.GitVersion@4

- task: knom.regexreplace-task.regex-replace.RegexReplace@3
  inputs:
    InputSearchPattern: 'src\Directory.Build.props'
    FindRegex: '<Version>.*</Version>'
    ReplaceRegex: '<Version>$(GitVersion.FullSemVer)</Version>'

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:PackageOutputPath=$(build.artifactstagingdirectory)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: Mairegger.Printing